// Code generated by protoc-gen-go. DO NOT EDIT.
// source: join_party.proto

package messages

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ = proto.Marshal
	_ = fmt.Errorf
	_ = math.Inf
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JoinPartyResponse_ResponseType int32

const (
	JoinPartyResponse_Unknown        JoinPartyResponse_ResponseType = 0
	JoinPartyResponse_Success        JoinPartyResponse_ResponseType = 1
	JoinPartyResponse_Timeout        JoinPartyResponse_ResponseType = 2
	JoinPartyResponse_LeaderNotReady JoinPartyResponse_ResponseType = 3
	JoinPartyResponse_UnknownPeer    JoinPartyResponse_ResponseType = 4
)

var JoinPartyResponse_ResponseType_name = map[int32]string{
	0: "Unknown",
	1: "Success",
	2: "Timeout",
	3: "LeaderNotReady",
	4: "UnknownPeer",
}

var JoinPartyResponse_ResponseType_value = map[string]int32{
	"Unknown":        0,
	"Success":        1,
	"Timeout":        2,
	"LeaderNotReady": 3,
	"UnknownPeer":    4,
}

func (x JoinPartyResponse_ResponseType) String() string {
	return proto.EnumName(JoinPartyResponse_ResponseType_name, int32(x))
}

func (JoinPartyResponse_ResponseType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4d19f49aa56fa857, []int{1, 0}
}

type JoinPartyRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinPartyRequest) Reset()         { *m = JoinPartyRequest{} }
func (m *JoinPartyRequest) String() string { return proto.CompactTextString(m) }
func (*JoinPartyRequest) ProtoMessage()    {}
func (*JoinPartyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d19f49aa56fa857, []int{0}
}

func (m *JoinPartyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinPartyRequest.Unmarshal(m, b)
}

func (m *JoinPartyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinPartyRequest.Marshal(b, m, deterministic)
}

func (m *JoinPartyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinPartyRequest.Merge(m, src)
}

func (m *JoinPartyRequest) XXX_Size() int {
	return xxx_messageInfo_JoinPartyRequest.Size(m)
}

func (m *JoinPartyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinPartyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinPartyRequest proto.InternalMessageInfo

func (m *JoinPartyRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type JoinPartyResponse struct {
	ID                   string                         `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Type                 JoinPartyResponse_ResponseType `protobuf:"varint,2,opt,name=type,proto3,enum=messages.JoinPartyResponse_ResponseType" json:"type,omitempty"`
	PeerIDs              []string                       `protobuf:"bytes,3,rep,name=PeerIDs,proto3" json:"PeerIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *JoinPartyResponse) Reset()         { *m = JoinPartyResponse{} }
func (m *JoinPartyResponse) String() string { return proto.CompactTextString(m) }
func (*JoinPartyResponse) ProtoMessage()    {}
func (*JoinPartyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d19f49aa56fa857, []int{1}
}

func (m *JoinPartyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinPartyResponse.Unmarshal(m, b)
}

func (m *JoinPartyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinPartyResponse.Marshal(b, m, deterministic)
}

func (m *JoinPartyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinPartyResponse.Merge(m, src)
}

func (m *JoinPartyResponse) XXX_Size() int {
	return xxx_messageInfo_JoinPartyResponse.Size(m)
}

func (m *JoinPartyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinPartyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinPartyResponse proto.InternalMessageInfo

func (m *JoinPartyResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *JoinPartyResponse) GetType() JoinPartyResponse_ResponseType {
	if m != nil {
		return m.Type
	}
	return JoinPartyResponse_Unknown
}

func (m *JoinPartyResponse) GetPeerIDs() []string {
	if m != nil {
		return m.PeerIDs
	}
	return nil
}

func init() {
	proto.RegisterEnum("messages.JoinPartyResponse_ResponseType", JoinPartyResponse_ResponseType_name, JoinPartyResponse_ResponseType_value)
	proto.RegisterType((*JoinPartyRequest)(nil), "messages.JoinPartyRequest")
	proto.RegisterType((*JoinPartyResponse)(nil), "messages.JoinPartyResponse")
}

func init() { proto.RegisterFile("join_party.proto", fileDescriptor_4d19f49aa56fa857) }

var fileDescriptor_4d19f49aa56fa857 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xb1, 0x4a, 0xc4, 0x40,
	0x10, 0x40, 0xdd, 0xe4, 0xf0, 0xbc, 0x39, 0x89, 0xeb, 0x54, 0x29, 0x43, 0xaa, 0x54, 0x29, 0xb4,
	0xb5, 0x4c, 0x13, 0x11, 0x39, 0xd6, 0xb3, 0xb1, 0x91, 0x78, 0x37, 0x48, 0x94, 0xdb, 0x59, 0x33,
	0x1b, 0x64, 0xbf, 0xd4, 0xdf, 0x91, 0x3d, 0x0c, 0x04, 0xaf, 0xdb, 0xc7, 0xbe, 0x37, 0x03, 0x03,
	0xfa, 0x83, 0x7b, 0xfb, 0xea, 0xba, 0xc1, 0x87, 0xda, 0x0d, 0xec, 0x19, 0x2f, 0x0e, 0x24, 0xd2,
	0xbd, 0x93, 0x94, 0x25, 0xe8, 0x7b, 0xee, 0xed, 0x26, 0x7e, 0x1a, 0xfa, 0x1a, 0x49, 0x3c, 0x66,
	0x90, 0xb4, 0x4d, 0xae, 0x0a, 0x55, 0xad, 0x4c, 0xd2, 0x36, 0xe5, 0x8f, 0x82, 0xeb, 0x99, 0x24,
	0x8e, 0xad, 0xd0, 0x7f, 0x0b, 0xef, 0x60, 0xe1, 0x83, 0xa3, 0x3c, 0x29, 0x54, 0x95, 0xdd, 0x54,
	0xf5, 0xb4, 0xa2, 0x3e, 0x49, 0xeb, 0xe9, 0xb1, 0x0d, 0x8e, 0xcc, 0xb1, 0xc2, 0x1c, 0x96, 0x1b,
	0xa2, 0xa1, 0x6d, 0x24, 0x4f, 0x8b, 0xb4, 0x5a, 0x99, 0x09, 0xcb, 0x17, 0xb8, 0x9c, 0xfb, 0xb8,
	0x86, 0xe5, 0xb3, 0xfd, 0xb4, 0xfc, 0x6d, 0xf5, 0x59, 0x84, 0xa7, 0x71, 0xb7, 0x23, 0x11, 0xad,
	0x22, 0x6c, 0xfb, 0x03, 0xf1, 0xe8, 0x75, 0x82, 0x08, 0xd9, 0x03, 0x75, 0x7b, 0x1a, 0x1e, 0xd9,
	0x1b, 0xea, 0xf6, 0x41, 0xa7, 0x78, 0x05, 0xeb, 0xbf, 0x34, 0x0e, 0xd7, 0x8b, 0xb7, 0xf3, 0xe3,
	0x39, 0x6e, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x62, 0x93, 0xfb, 0x4e, 0x22, 0x01, 0x00, 0x00,
}
